### ISSUE TITLE
Proč to není pole elementů Square?

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#11]
https://github.com/lizzykorotkikh/Tic-Tac-Toe/blob/3a6ca338335bfce06a095d4d4a3151c85e95765f/Tic%20Tac%20Toe%20sharp.cs#L22

**Comment by lizzykorotkikh** [comment]
Protože jenom sudé čísla jsou Square elementy

**Comment by fan1x** [comment]
Aha... To mi uniklo. Tím spíš je to ještě ošklivější kód... V poli by měli být elementy stejného typu, neměli by se míchat 2 druhy. 
Jak to napravit, vytvořit si pomocnou strukturu. Vždycky se používají jak symbol na počet, tak se logicky nabízí to spojit do jednoho, např:
```
private int [] combinations = new int[] {2, 2, 2, 1, 1, 2, 3, 0 };//2 Nought, 2 Cross, 1 Nought, 3 Empty ( which means in line - 2 Noughts => 1 Empty, etc.) 

-->

struct Combination
{
    Square symbol;
    int count;
}

private Combination[] combinations = new Combination[]{ { Square.Nought, 2 }, ... }
```

**Comment by lizzykorotkikh** [comment]
Okay, chápu
