### ISSUE TITLE
Vytvořit strukturu/třídu "Coordinates"

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#13]
Souřadnice X, Y jsou vždy používány společně --> vytvořit pro ní struktruru, která obsahuje oba dva elementy
např:
```
struct Coordiantes 
{
  int x;
  int y;
}
```

**Comment by lizzykorotkikh** [comment]
Na to přemýšlím. Ještě nevidím výhodu takové struktury.

**Comment by fan1x** [comment]
Výhody: 
- je to přehlednější (když se na to koukne člověk, který tomu nepochopí na první pohledco znamená `x`, `y`. Nadruhou stranu, když je to structura `Coordinates` tak mu dojde, že jsou to souřadnice 😄 )
- je jasné, že musí být souřadnice použité spolu
- nemůže se zapomenou na druhou souřadnici
- můžu vložit funkce spojené se souřadnicemi dovnitř (vyrobit třídu) - přidat funkci `validate()` atd...
- je to objektový přístup
- předává se to jako jeden parametr ve funkci

**Comment by lizzykorotkikh** [comment]
> Výhody:
> 
>     * je to přehlednější (když se na to koukne člověk, který tomu nepochopí na první pohledco znamená `x`, `y`. Nadruhou stranu, když je to structura `Coordinates` tak mu dojde, že jsou to souřadnice smile )
> 
>     * je jasné, že musí být souřadnice použité spolu
> 
>     * nemůže se zapomenou na druhou souřadnici
> 
>     * můžu vložit funkce spojené se souřadnicemi dovnitř (vyrobit třídu) - přidat funkci `validate()` atd...
> 
>     * je to objektový přístup
> 
>     * předává se to jako jeden parametr ve funkci

aa vidím
