### ISSUE TITLE
Jak pracuješ s GITem

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#14]
Zdá se mi, že s GITem pracuješ špatně. Jak s ním pracuješ? Ideální je stahnout si nějakého clienta (TortoiseGIT, GIT, ...) a ten používat k nahrávání souborů.

**Comment by lizzykorotkikh** [comment]
> Zdá se mi, že s GITem pracuješ špatně. Jak s ním pracuješ? Ideální je stahnout si nějakého clienta (TortoiseGIT, GIT, ...) a ten používat k nahrávání souborů.

Je to můj první pokus, tak pro mě není dokonce nejasně, jak všechno funguje. Myšlenka je jasná, ale není to intuitivní.

**Comment by fan1x** [comment]
Není potřeba řešit teď, ale určitě doporučuji se v nejbližší budoucnosti s GITem seznámit - přečist například: https://git-scm.com/doc nebo jiné dokumenty o tom, jak se s ním pracuje.
