### ISSUE TITLE
Rozdělit do více souborů

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#15]
Obecně je dobré rozdělit třeba zhruba 1 třída na 1 soubor

**Comment by fan1x** [comment]
Tohle pořád není dořešené...

**Comment by lizzykorotkikh** [comment]
> Tohle pořád není dořešené...

Tak jsem už rozdělila, mám tam dvě třídy, jsou v různých souborech. Nebo ještě víc rozdělit?

**Comment by fan1x** [comment]
Jojo, to staci
