### ISSUE TITLE
Po spuštění (zmačknutí tlačítka) je GUI rozbité, pak se už opraví...

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#17]
![e4](https://user-images.githubusercontent.com/2750870/65554602-5c335800-df2a-11e9-8785-ab80bc72f3b0.png)

**Comment by fan1x** [comment]
V čem byl problém?

**Comment by lizzykorotkikh** [comment]
> V čem byl problém?

Jak jste řekl, problém byl s tím Invalidate a OnPaint, dlouho jsem hledala, jak ho můžu vyřešit, na štěstí jsem našla

**Comment by fan1x** [comment]
No, ale co tam bylo za problém s tím Invalidate a OnPaint?

**Comment by lizzykorotkikh** [comment]
Jak jsem pochopila, že ten Invalidate udělá update(posílá message do toho OnPaint metoda) okna, ale rychost tohle zprávy není stačí, aby ten OnPaint metod udělá to v čas, tak udělal jsem ten update konkrétní v té metodě
