### ISSUE TITLE
Pridat dalsi funkcionalitu

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#2]
Z mailu jsme se domlouvali, ze to bude umet:

`
Není problém to psát v čemkoliv, dokonce je to i vítáno, C++ je ok. Navrhuji tedy například - konzolové Tic-Tac-Toe libovolné velikosti (vybere se na začátku), buď proti druhému hráči nebo proti počítači. Počítač bude pomocí nějaké algoritmu (prohledávání s ořezáváním třeba?) schopen hrát proti hráči. Půjde nastavit hloubka prohledávání a ořezávání? Šlo by? Pokud bys nechtěla řešit hru proti počítači, tak můžeme rozšířit hru pro více hráčů například o ukládání apod.)
`

**Comment by fan1x** [comment]
Ideálně třeba použít nějaký chytřejší algoritmus na větší plochy (minimax apod...)

**Comment by fan1x** [comment]
> Psala jsem Vam "Ten algoritmus počítače není minimax nebo něco takového, je to maximálně přibližná strategie jakýkoliv člověka.
    Počítač nemá hlavní cíl vyhrát, jenom udělá maximálně všechno, aby se to stalo, ale není vždycky."
    Nedává to smysl hrát, když to bude minimax algoritmus, ale je to jenom můj názor.

Viz podmínky programu. Není problém, když to nebude minimax, důležité je, aby algoritmus fungoval i pro velké piškvorky="Tic-Tac-Toe libovolné velikosti" jsou vlastně piškvorky. 
A aby fungoval správně a i nějak rozumně ( aby vyhrál, když má šanci, apod...)

**Comment by lizzykorotkikh** [comment]
> > Psala jsem Vam "Ten algoritmus počítače není minimax nebo něco takového, je to maximálně přibližná strategie jakýkoliv člověka.
> > Počítač nemá hlavní cíl vyhrát, jenom udělá maximálně všechno, aby se to stalo, ale není vždycky."
> > Nedává to smysl hrát, když to bude minimax algoritmus, ale je to jenom můj názor.
> 
> Viz podmínky programu. Není problém, když to nebude minimax, důležité je, aby algoritmus fungoval i pro velké piškvorky="Tic-Tac-Toe libovolné velikosti" jsou vlastně piškvorky.
> A aby fungoval správně a i nějak rozumně ( aby vyhrál, když má šanci, apod...)

Nepsala jsem, že to bude umět hrát "Tic-Tac-Toe libovolné velikosti". Psala jsem jenom, že bude hra s počítačem a hra s kámošem.. 
Teď algoritmus, když má šanci, tak vyhraje

**Comment by fan1x** [comment]
> Nepsala jsem, že to bude umět hrát "Tic-Tac-Toe libovolné velikosti". Psala jsem jenom, že bude hra s počítačem a hra s kámošem..

To sice ano, ale já jsem na ten mail odpovídal (viz nahoře), že bych si představoval tam přidat ještě další věci (protože jinak by to bylo dost jednoduché). Potom jsem už žádnou odpověď nedostal, takže jsem předpokládal, že s tím souhlasíš... Pokud jsi s tím nesouhlasila, tak jsi měla odepsat, což se nestalo... 

Každopádně, pokud bys chtěla přidat jinou funkcionalitu, tak s tím nemám problém, ale musí to být dostatečně složité na zápočtový program 😄 Taky pozor na to, že se blíží konec školního roku.

**Comment by lizzykorotkikh** [comment]
> To sice ano, ale já jsem na ten mail odpovídal (viz nahoře), že bych si představoval tam přidat ještě další věci (protože jinak by to bylo dost jednoduché). Potom jsem už žádnou odpověď nedostal, takže jsem předpokládal, že s tím souhlasíš... Pokud jsi s tím nesouhlasila, tak jsi měla odepsat, což se nestalo...
> 
> Každopádně, pokud bys chtěla přidat jinou funkcionalitu, tak s tím nemám problém, ale musí to být dostatečně složité na zápočtový program smile Taky pozor na to, že se blíží konec školního roku.

Promiň, možná je to bylo nedorozumění. Avšak je to projekt z prvního semestru, tak na konci 1 semestru, nevěděla jsem co je grafika nebo co je c# vůbec, proto, myslím, projekt je hodný po složitosti. Ještě k tomu je už září a dopisování je pomalá, proto už nebude dost času změnit celý kód.

**Comment by fan1x** [comment]
> však je to projekt z prvního semestru, tak na konci 1 semestru, nevěděla jsem co je grafika nebo co je c# vůbec, proto, myslím, projekt je hodný po složitosti.

No, já si nemyslím, že je to dostatečně složitý program, který lze uznat jako zápočtový. Samotný program bez GUI by měl student zvládnout jako zápočtovou písemku, to znamená třeba za 3 hodiny...
Přidání GUI znamená, že se musí seznámit s programováním GUI. Jelikož se jedná o veeelmi jednoduchý program (který zatím ani nefunguje....) - obsahuje formulář a 9 tlačítek, tak to má člověk hotové třeba za 16 hodin práce. 
Zápočťák není určitě program, který naprogramuješ za 2 dny... 
Navíc, jste měli v druhém semestru práci se C#, takže ses to ani nemusela učit sama...
Jinak, přidání možnosti vybrat velikost pole není vůbec nic složitého... Mělo by to být jen pár úprav. Je to spíš kontrola pro mě, že rozumíš programování a naprogramovanému kódu (což zatím bohužel moc nevypadá 😞 )

**Comment by fan1x** [comment]
Už to vypadá pěkně, jen dodělat možnost přidat libovolnou velikost a s funkcioanlitou jsem spokojený 👍

**Comment by fan1x** [comment]
Už je super, že velikost pole může být libovolná ale měla by vyplnit celé okno (když dám okno na fullscreen), tak je pořád stejně velké - není potřeba řešit zvětšování/zmenšování při hře, ale v době generování pole by to mělo být možné....

**Comment by fan1x** [comment]
![image](https://user-images.githubusercontent.com/2750870/65728299-c1b64e80-e0ba-11e9-900b-e65f88621a86.png)
Porad to neni pres cele okno... Ja delam ze zapnu hru, maximalizuji pres celou plochu a pak nastavim cislo (treba 100) a chtel bych, aby to bylo pres celou plochu...
