### ISSUE TITLE
Rozdělit to nějak do funkcí a neopakovat podobný kód znova a znova

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#6]
https://github.com/lizzykorotkikh/Tic-Tac-Toe/blob/f9afb867a4a1455b5276c791176a85730515bed3/Tic-Tac-Toe_Elizaveta_Korotkikh_Prog1.cpp#L131

**Comment by fan1x** [comment]
Podobný problém - rozdělit do více souborů. například jedna třída na jeden soubor

**Comment by lizzykorotkikh** [comment]
Řekněte mi, prosím, kde konkrétně je "opakování" kódu, protože já to nevidím

**Comment by fan1x** [comment]
> Podobný problém - rozdělit do více souborů. například jedna třída na jeden soubor

Napsal jsem to možná drobet zmateně pod tohle issue, omlouvám se. Jde o to, rozdělit třídy do více souborů, jako se to dělá v C#. Zhruba se dělá 1 třída = 1 soubor.

**Comment by lizzykorotkikh** [comment]
> > Podobný problém - rozdělit do více souborů. například jedna třída na jeden soubor
> 
> Napsal jsem to možná drobet zmateně pod tohle issue, omlouvám se. Jde o to, rozdělit třídy do více souborů, jako se to dělá v C#. Zhruba se dělá 1 třída = 1 soubor.

Okay, ted' chápu
