### ISSUE TITLE
Přidat i projektové a solution z vývojového prostředí (sln,...)

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#8]
Přidat i projektové soubory, aby to šlo jednodušše otevřít ve výjovém prostředí

**Comment by fan1x** [comment]
Když používáš nějaké prostředí (pochopil jsem Geany), tak má k dispozici i nějaké pomocné soubory. Tak ty se nahrávají do GITu také... Geany asi bude mít taky nějaký projektový soubor..

Jde o to, aby, když si stahnu Geany, tak abych mohl jednodušše spustit celý projekt a zkompilovat si ho u sebe na počítači.

**Comment by lizzykorotkikh** [comment]
Zdá se mi, že už chápu

**Comment by lizzykorotkikh** [comment]
Vytvořila jsem soubor zip, ve kterém jsou .cs a .geany soubory, poslední slouží k otevírání celého projektu. Doufám že je to tohle, co jste chtěl

**Comment by fan1x** [comment]
Ne, pořád to není úplně ono. Není potřeba nic zabalovat... :) 
Zkus si někde přečíst v rychlosti, jak se pracuje s GITem, nějaké základy. Když programuješ, tak máš složku, kde jsou uložené zdrojové kódy, pak jsou tam i nějaké další soubory (od vývojových prostředí, binárky, ...). Stačí tedy vzít tuhle složku a nahrát ji do GITu. Ale, nahrát tam pouze soubory, které jsou potřeba ke kompilaci v daném prostředí - zdrojové soubory, projektový soubor. 
Vlastně tedy potom v GITu bude to samé, co je v zabalené sloužce, bez té binárky (exe souboru)

**Comment by fan1x** [comment]
Další věc, proč jsou k dispozici 2 soubory: `Tic Tac Toe sharp.cs` a `TicTactoe.cs`, který z nich mám použít? Nechat pouze ten, který mám použít.

**Comment by lizzykorotkikh** [comment]
> Ne, pořád to není úplně ono. Není potřeba nic zabalovat... :)
> 
> Vlastně tedy potom v GITu bude to samé, co je v zabalené sloužce, bez té binárky (exe souboru)

.. ještě dokonce nechápu, ale zkusím znovu

**Comment by fan1x** [comment]
Uz je to super 👍
