### ISSUE TITLE
Po spuštění je GUI rozbité

### ISSUE THREAD

**Issue by fan1x** [lizzykorotkikh/Tic-Tac-Toe#9]
![error2](https://user-images.githubusercontent.com/2750870/62820924-2d287900-bb6c-11e9-8442-692070d5bbff.png)

**Comment by fan1x** [comment]
Po dohrání taky

![error3](https://user-images.githubusercontent.com/2750870/62820959-a031ef80-bb6c-11e9-8286-c9082892a10e.png)

**Comment by fan1x** [comment]
No, tak je potřeba to zkusit třeba na jiném počítači, případně to nějak odladit... 
Zkusit vyclonovat do čisté složky a zkusit znova...
Bude to asi způsobeno nějak různou velikostí na různých počítačích (myslím)

**Comment by lizzykorotkikh** [comment]
> No, tak je potřeba to zkusit třeba na jiném počítači, případně to nějak odladit...
> Zkusit vyclonovat do čisté složky a zkusit znova...
> Bude to asi způsobeno nějak různou velikostí na různých počítačích (myslím)

Nemám jiný počítač, ale zkusím něco změnit

**Comment by lizzykorotkikh** [comment]
Napsala jsem grafickou část trošku jinak, doufám, že bude to u vás správně fungovat. 
Nějaký jiný počítač jsem nenašla, bohužel.

**Comment by fan1x** [comment]
Pořád mám bohužel stejný problém... 
Buď můžeš zkusit najít problém v kódu a nebo doporučuji nějak zkusit odladit, připadně například jiný překladač (zkusit Visual Studio např.) Já to spouštím normálně na Windows 10.

**Comment by lizzykorotkikh** [comment]
> Pořád mám bohužel stejný problém...
> Buď můžeš zkusit najít problém v kódu a nebo doporučuji nějak zkusit odladit, připadně například jiný překladač (zkusit Visual Studio např.) Já to spouštím normálně na Windows 10.

Nevím co s tím udělat. Měla jsem projekt z Prog2, psala jsem tam taky v Geany a používala jsem komplikovanou grafiku, všechno bylo v pohodě. Jak už jsem psala nemám jiný počítač a spustit VS taky nemůžu. Jenom co můžu, tak přijít a ukázat jak funguje to u mě.

**Comment by fan1x** [comment]
No, program který funguje pouze na jednom počítači a ještě náhodou je na houby... 

Každopádně jsem na to koukal a problém je v kombinaci metod `Invalidate()` (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.invalidate?view=netframework-4.8) a ve funkci `OnPaint()`, respektive v tom příslušném `Paint` eventu (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.paint?view=netframework-4.8). 

Najdeš v čem může být problém?

**Comment by fan1x** [comment]
Funguje, az tedy na prvni spusteni viz #17
